# Generated by Django 5.1.1 on 2024-09-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='timestamp',
        ),
    ]
