# Generated by Django 5.1.1 on 2024-09-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0002_remove_read_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='turn_signal',
            field=models.FloatField(),
        ),
    ]
