# Generated by Django 5.1.1 on 2024-09-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0003_alter_read_turn_signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='braking',
        ),
        migrations.RemoveField(
            model_name='read',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='read',
            name='turn_signal',
        ),
    ]
