# Generated by Django 5.1.1 on 2024-09-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0002_remove_read_timestamp'),
        ('comunication', '0004_remove_read_braking_remove_read_speed_and_more'),
    ]

    operations = [
    ]
