# Generated by Django 5.1.1 on 2024-09-30 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0005_merge_20240930_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='braking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='read',
            name='client',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='read',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='read',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='read',
            name='turn_signal',
            field=models.IntegerField(default=0),
        ),
    ]
