# Generated by Django 5.1.1 on 2024-10-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0007_alter_read_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
