# Generated by Django 5.1.1 on 2026-09-22 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0008_alter_read_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='read',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reads', to='comunication.car'),
        ),
        migrations.CreateModel(
            name='CarAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='comunication.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
