# Generated by Django 5.1.1 on 2026-09-22 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('comunication', '0009_car_read_car_carassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.company'),
        ),
    ]
