# Generated by Django 5.1.1 on 2026-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunication', '0010_car_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
